import { useState } from "react";
import type { Campaign, View } from "../types";
import { CompanyLogo } from "./CompanyLogo";
import { Header } from "./Header";

type ResultsProps = {
  campaign: Campaign;
  onNavigate: (view: View) => void;
};

type Tab = "social" | "strategy" | "analytics";

export function CampaignResults({ campaign, onNavigate }: ResultsProps) {
  const [tab, setTab] = useState<Tab>("social");

  return (
    <>
      <Header
        eyebrow="Campaign Output"
        title={campaign.topic}
        description="Review company-aware assets generated by the agent workflow."
        action={<button onClick={() => onNavigate("create")} className="btn-primary"><i className="fas fa-plus" /> New Campaign</button>}
      />

      <section className="mb-6 grid gap-4 md:grid-cols-3">
        <SummaryCard title="Company" value={campaign.company?.name || "Company"} icon="fa-building" companyLogo />
        <SummaryCard title="Status" value={campaign.status} icon="fa-circle-check" />
        <SummaryCard title="Score" value={campaign.score ? String(campaign.score) : "Pending"} icon="fa-chart-simple" />
      </section>

      <div className="card">
        <div className="mb-6 flex flex-wrap gap-2 border-b border-slate-200 pb-4">
          {(["social", "strategy", "analytics"] as Tab[]).map((item) => (
            <button key={item} onClick={() => setTab(item)} className={tab === item ? "tab-active" : "tab"}>
              {item}
            </button>
          ))}
        </div>

        {tab === "social" ? <SocialAssets assets={campaign.assets} /> : null}
        {tab === "strategy" ? <JsonBlock value={campaign.assets.strategy || campaign.assets.research || campaign.assets} /> : null}
        {tab === "analytics" ? <JsonBlock value={campaign.assets.analytics || {}} /> : null}
      </div>

      <div className="mt-6 flex gap-3">
        <button onClick={() => onNavigate("campaigns")} className="btn-secondary">View Campaigns</button>
        <button onClick={() => onNavigate("dashboard")} className="btn-secondary">Dashboard</button>
      </div>
    </>
  );

  function SummaryCard({ title, value, icon, companyLogo }: { title: string; value: string; icon: string; companyLogo?: boolean }) {
    return (
      <div className="card flex items-center gap-4">
        {companyLogo ? <CompanyLogo company={campaign.company} /> : <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-950 text-white"><i className={`fas ${icon}`} /></div>}
        <div>
          <p className="text-sm font-semibold text-slate-500">{title}</p>
          <p className="font-bold capitalize">{value}</p>
        </div>
      </div>
    );
  }
}

function SocialAssets({ assets }: { assets: Record<string, unknown> }) {
  const social = isRecord(assets.social) ? assets.social : {};
  const entries = Object.entries(social);

  if (entries.length === 0) {
    return <p className="text-sm text-slate-500">No social assets generated.</p>;
  }

  return (
    <div className="space-y-6">
      {entries.map(([platform, value]) => (
        <section key={platform}>
          <div className="mb-3 flex items-center gap-2">
            <span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">{platform}</span>
          </div>
          {isRecord(value) ? (
            <div className="grid gap-4 xl:grid-cols-2">
              {Object.entries(value)
                .filter(([key]) => key.startsWith("variant"))
                .map(([key, text]) => (
                  <article key={key} className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
                    <div className="border-b border-slate-200 bg-slate-50 px-4 py-3">
                      <span className="text-sm font-bold uppercase tracking-wide text-slate-600">{key.replace("_", " ")}</span>
                    </div>
                    <pre className="whitespace-pre-wrap p-5 font-sans text-sm leading-7 text-slate-800">{String(text)}</pre>
                  </article>
                ))}
            </div>
          ) : (
            <JsonBlock value={value} />
          )}
        </section>
      ))}
    </div>
  );
}

function JsonBlock({ value }: { value: unknown }) {
  return <pre className="max-h-[520px] overflow-auto rounded-2xl bg-slate-950 p-5 text-sm leading-6 text-slate-100">{JSON.stringify(value, null, 2)}</pre>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}
